//FASE1
export const EXPERIMENTO_STATUS_EM_EXECUCAO = "EM_EXECUCAO";
export const MOTIVO_FOCO_COMPLETO = "FOCOU";
export const MOTIVO_TEMPO_ESGOTADO = "TEMPO";

//FASE2
export const STATUS_RODADA1 = "RODADA1";
export const STATUS_RODADA2 = "RODADA2";
export const STATUS_FINALIZADO = "FINALIZADO";
